// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1:string):Promise<string>;

export function Login(arg1:string):Promise<boolean>;

export function RunAudit():Promise<string>;

export function RunExploit(arg1:string):Promise<string>;

export function RunScan(arg1:string):Promise<string>;
