// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Login(arg1) {
  return window['go']['main']['App']['Login'](arg1);
}

export function RunAudit() {
  return window['go']['main']['App']['RunAudit']();
}

export function RunExploit(arg1) {
  return window['go']['main']['App']['RunExploit'](arg1);
}

export function RunScan(arg1) {
  return window['go']['main']['App']['RunScan'](arg1);
}
